config:
  image: ubuntu:18.04
  project_name: some-rails-project



secrets:
  my_secret:
    service: test-lior2
    path: kv/dev
    key: env
    
environment:
  RAILS_ENV: test
  GIT_COMMITTER_NAME: a
  GIT_COMMITTER_EMAIL: b
  LANG: C.UTF-8
  GOCACHE: "${PWD}/.cache"

jenkinsEnvironment:
  - JENKINS_URL

timeout: 600

steps:
  build:
    image: golang:1.12
    commands:
      - env
      - go build
  test:
    image: golang:1.12
    commands:
      - go mod download
      - ./test.sh
  deploy:
    image: amazon/aws-cli
    commands:
      - aws ec2 describe-tags

          
stages:
  stage1:
    - build
    - test
  stage2:
    - deploy