config:
  image: ubuntu:18.04
  project_name: some-rails-project

services:
  - mssql

secrets:
  my_secret:
    service: test-lior2
    path: kv/dev
    key: env

stages:
  job_a:
    - update:
      image: ubuntu:18.04
      commands:
        - ls -la
        - echo "help"
    - aws:
      image: amazon/aws-cli
      commands:
        - aws ec2 describe-tags
    - vault:
      image: ubuntu:18.04
      commands:
        - echo "###########"
        - echo $my_secret
  job_b:
    - final:
      image: ubuntu:18.04
      commands:
        - echo "final"
    
environment:
  RAILS_ENV: test
  GIT_COMMITTER_NAME: a
  GIT_COMMITTER_EMAIL: b
  LANG: C.UTF-8

jenkinsEnvironment:
  - JENKINS_URL

timeout: 600
