config:
  image: ubuntu:18.04
  project_name: some-rails-project

services:
  - mssql

secrets:
  my_secret:
    service: test-lior2
    path: kv/dev
    key: env
    
environment:
  RAILS_ENV: test
  GIT_COMMITTER_NAME: a
  GIT_COMMITTER_EMAIL: b
  LANG: C.UTF-8

jenkinsEnvironment:
  - JENKINS_URL

timeout: 600

steps:
  build:
    image: ubuntu
    commands:
      - echo "build"

stages:
  stage1:
    - build
    - test
  stage2:
    - deploy