config:
  image: ubuntu:18.04
  project_name: some-rails-project

services:
  - mssql

steps:
  update:
    image: ubuntu:18.04
    commands:
      - ls -la
      - echo "help"
  aws:
    image: amazon/aws-cli
    commands:
      - ec2 describe-tags


environment:
  RAILS_ENV: test
  GIT_COMMITTER_NAME: a
  GIT_COMMITTER_EMAIL: b
  LANG: C.UTF-8

jenkinsEnvironment:
  - JENKINS_URL

timeout: 600
