config:
  image: ubuntu:18.04
  project_name: jenkins



secrets:
  my_secret:
    service: test-lior2
    path: kv/dev
    key: env
    
environment:
  RAILS_ENV: test
  LANG: C.UTF-8


jenkinsEnvironment:
  - JENKINS_URL

timeout: 600

steps:
  finish:
    image: ubuntu:18.04
    commands:
      - echo "I'm finished" 
  build:
    image: golang:1.12
    commands:
      - git show -s --format='%ae'
      - env
      - go build -o jenkins
  test:
    image: golang:1.12
    commands:
      - go mod download
      - ./test.sh
  deploy:
    image: amazon/aws-cli
    commands:
      - echo ${my_secret}
      - aws s3 cp jenkins s3://jenkins-lior/
          
stages:
  build_and_test:
    steps:
      - build
      - test
  deploy:
    steps:
      - deploy
    when:
      branch: master